### ISSUE TITLE
Can not compile 1.5.0 with cmake version 3.24.2

### ISSUE THREAD

**Issue by rubyFeedback** [tjko/jpegoptim#113]
Trying it fails with:

    cmake -DCMAKE_INSTALL_PREFIX=/usr .

    CMake Deprecation Warning at CMakeLists.txt:1 (cmake_minimum_required):
      Compatibility with CMake < 2.8.12 will be removed from a future version of
      CMake.

      Update the VERSION argument <min> value or use a ...<max> suffix to tell
      CMake that the project does not need compatibility with older versions.

    CMake Error at CMakeLists.txt:9 (set_target_properties):
      set_target_properties called with incorrect number of arguments.

    -- Configuring incomplete, errors occurred!
    See also "/home/x/Temp/rbt/jpegoptim-1.5.0/CMakeFiles/CMakeOutput.log".
    make: *** No targets specified and no makefile found.  Stop.

**Comment by tjko** [comment]
Recently merged pull request https://github.com/tjko/jpegoptim/pull/115, should have fixed this?
