### ISSUE TITLE
Destination path parameter does not work properly

### ISSUE THREAD

**Issue by kunapyanov** [tjko/jpegoptim#129]
Hi! 
I found bug: when I set destination path via -d or --dest output doesn't saves files in directory but adds folder name as prefix. 
Example: 
`jpegoptim -v -dconverted ./to-convert/file.jpg`
will save file as _./convertedfile.jpg_ and _converted_ directory will be empty. 
I found where is the problem: it's jpegoptim.c:347. sizeof(dest_path) returns 8 because here dest_path is pointer, not a char array like in main

**Comment by tjko** [comment]
Thanks for the fix. Change merged.
