### ISSUE TITLE
Option to output to another filename

### ISSUE THREAD

**Issue by talha-asad** [tjko/jpegoptim#14]
Currently you support batch image processing nicely by offering destination directory option, however if a user wants to optimize just a single image with a different file name, he can't. I think having 2 parameters one for input and one for output can help in this case and it seems reasonable to have this support in this awesome optimizer.

**Comment by vortex852456** [comment]
To use stdin/stdout you have to use a shell. The binary itself is not capable of outputting to another filename, which in my opinion is a weakness/missing feature.

**Comment by ravgeetdhillon** [comment]
If anyone is stuck with this, you can get a little creative by doing this.

1. Create a copy of your original image and rename it to your intended output file name.
2. Optimize the copied version of your original image.

Here is a small bash script:

```bash
img='test.jpg'
cp $img ${img%.*}-optimized.jpg
jpegoptim ${img%.*}-optimized.jpg
```
