### ISSUE TITLE
Progressive JPEG files by default?

### ISSUE THREAD

**Issue by wwinniww** [tjko/jpegoptim#142]
I use the windows 64 bit compile of jpegoptim 1.5.3

I noticed that every optimized jpeg file is progressive, but I don't specify --all-progressive as  command line parameter.
Shouldn't be the default operation unless specified otherwise to keep sequential JPEG instead of converting every JPEG file into progressive JPEG?

**Comment by tjko** [comment]
I couldn't replicate this. Are you perhaps using mozjpeg, and not libjpeg? (I was testing with jpegoptim compiled against latest libjpeg).

**Comment by wwinniww** [comment]
Thanks.
Nice to have feature might be to display both normal and progressive jpeg file sizes when --no-action parameter is specified.

**Comment by tjko** [comment]
I think this should now be fixed.  If you want to test the fix, you can find binaries here: https://github.com/tjko/jpegoptim/actions/runs/4559486709

**Comment by tjko** [comment]
Maybe better (less intrusive) is to implement new option like _--preserve-mode_  that could be used if someone wants to prevent JPEG changing from normal to progressive during optimization.   Since most users likely just want smallest possible file (by default) and progressive vs non-progressive JPEG is not a factor at all... (?)

**Comment by wwinniww** [comment]
Hello.
The only drawback when it comes to this is: 
Progressive JPEG images takes noticeably longer to decode compared to normal JPEG.
I don't know if every JPEG decoder out there is able to decode progressive JPEG.

I think that a --preserve-mode switch is a good idea.

An other minor thing, maybe the help option of the program should not display unavailable option,
in the case jpegoptim is compiled without support of arithmetic coding,
why should help show that option?

Thanks.

**Comment by starleafs** [comment]
I noticed that progressive jpegs not showing correctly on mac/ios
jpegoptim version 1.5.3 winows

When I covert images using standard method (jpegoptim.exe --max=90), I received images display wired colour lines opening with mac/ios， but images display correclty on PC.
After reading this post, i use non-progressive method (jpegoptim.exe --max=90 --all-normal), I received images display correctly both on PC/Mac

is it a bug?

![IMG_0841-progressive(screenshot from mac)](https://user-images.githubusercontent.com/23342239/232417167-ef80e132-8377-4294-a468-908738c95ac5.jpg)
![IMG_0841-progressive(screenshot from PC)](https://user-images.githubusercontent.com/23342239/232417268-f5727983-b0cc-481d-838e-cc2f89c38111.jpg)
![IMG_0841-progressive](https://user-images.githubusercontent.com/23342239/232417403-d0bba450-f6f8-4377-b7d4-b1c34f2c4fb1.JPG)

**Comment by tjko** [comment]
> I noticed that progressive jpegs not showing correctly on mac/ios jpegoptim version 1.5.3 windows
> 
> When I covert images using standard method (jpegoptim.exe --max=90), I received images display wired colour lines opening with mac/ios， but images display correctly on PC. After reading this post, i use non-progressive method (jpegoptim.exe --max=90 --all-normal), I received images display correctly both on PC/Mac
> 
> is it a bug? I've attched screenshot and sample images below

@starleafs, can you provide the actual image file(s)?  So I could test, if I can reproduce the issue you're seeing.

**Comment by wwinniww** [comment]
Hello,
sorry Timo. I can’t check that. I don’t own devices from Apple or have Access to them Right now.


Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows

________________________________
Von: Timo Kokkonen ***@***.***>
Gesendet: Monday, October 30, 2023 5:18:18 AM
An: tjko/jpegoptim ***@***.***>
Cc: wwinniww ***@***.***>; Author ***@***.***>
Betreff: Re: [tjko/jpegoptim] Progressive JPEG files by default? (Issue #142)


I noticed that progressive jpegs not showing correctly on mac/ios jpegoptim version 1.5.3 windows

When I covert images using standard method (jpegoptim.exe --max=90), I received images display wired colour lines opening with mac/ios， but images display correctly on PC. After reading this post, i use non-progressive method (jpegoptim.exe --max=90 --all-normal), I received images display correctly both on PC/Mac

is it a bug? I've attched screenshot and sample images below

@starleafs<https://github.com/starleafs>, can you provide the actual image file(s)? So I could test, if I can reproduce the issue you're seeing.

―

**Comment by starleafs** [comment]
> > I noticed that progressive jpegs not showing correctly on mac/ios jpegoptim version 1.5.3 windows
> > When I covert images using standard method (jpegoptim.exe --max=90), I received images display wired colour lines opening with mac/ios， but images display correctly on PC. After reading this post, i use non-progressive method (jpegoptim.exe --max=90 --all-normal), I received images display correctly both on PC/Mac
> > is it a bug? I've attched screenshot and sample images below
> 
> @starleafs, can you provide the actual image file(s)? So I could test, if I can reproduce the issue you're seeing.

Hello, I tested again with jpegoptim version  1.5.5 and I think this bug was fixed  on version v1.5.4 (Fix mozjpeg not preserving JPEG mode (progressive vs normal) by @tjko in #143 

thanks.
