### ISSUE TITLE
Release Page Linux binaries crashing on ubuntu 20.04

### ISSUE THREAD

**Issue by UnknownPlatypus** [tjko/jpegoptim#144]
Hey !

So I'm a little bit down the rabbit-hole but I'm having trouble using the linux binaries from the [release page](https://github.com/tjko/jpegoptim/releases/tag/v1.5.3). When I try to execute the binaries I get these errors: 

```sh
./jpegoptim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by ./jpegoptim)
./jpegoptim: /lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by ./jpegoptim)
```

So I did some investigation and it appears that build made using `ubuntu-latest(22.04)` are not compatible with `ubuntu20.04` because the GLIBC version used to make the build is not available on older ubuntu versions. 

I tried running the CI [using ubuntu-20.04](https://github.com/UnknownPlatypus/jpegoptim/actions/runs/4458089044) and after that, the resulting binaries are working correctly on both ubuntu 20.04 and ubuntu 22.04 (I tested both using ubuntu docker images).

I'm not an expert in building binaries and there may be an underlying problem that would have to be solved in some other way, but in the meantime, would you accept a PR changing the OS used in the CI from `ubuntu-latest` to `ubuntu-20.04`?

For context, I'm trying to build a python wrapper for jpegoptim to allow easy usage with the [pre-commit](https://github.com/pre-commit/pre-commit) framework and wanted to do something really similar to [shellcheck-py](https://github.com/shellcheck-py/shellcheck-py) which rely on binaries uploaded by [shellcheck on there Release page](https://github.com/koalaman/shellcheck/releases).

PS: I checked the GLIBC version available for a few ubuntu distro (available via github actions) using `ldd --version`:
- `ubuntu 22.04 -> GLIBC 2.35`
- `ubuntu 20.04 -> GLIBC 2.31`

Thanks for the wonderful package.
Cheers

**Comment by tjko** [comment]
Yes, it probably better not use "latest" to build, but previous release etc, so the precompiled binaries will work for more users....

If you can make a PR on this, that would be great.
