### ISSUE TITLE
Unable to strip photos in HEIC format.

### ISSUE THREAD

**Issue by huabin** [tjko/jpegoptim#173]
Hello,

First thank you so much for creating this, I love it.

But there's an error, it seems unable to strip photos in HEIC format.

### What did I do?

Run the command `jpegoptim -s IMG_9230.HEIC`

### What did I get?

```
IMG_9230.HEIC  [ERROR]
```

### What have I tried?

I tried several photos in HEIC format, all have this issue. And I tried to convert the photo's format to jpg. It works well.

**Comment by Oldes** [comment]
Unfortunately `heic` image format is not `jpeg` and so you should not expect, that `jpegoptim` will work with it.
You will get the same error with any non `jpeg` input.. like:
```
>jpegoptim -s jpegoptim.exe
jpegoptim.exe  [ERROR]
```

**Comment by tjko** [comment]
HEIC seems to be Apple's variant of [HEIF](https://en.wikipedia.org/wiki/High_Efficiency_Image_File_Format).  I don't see _jpegoptim_ supporting HEIC, unless support for it is added to existing JPEG libraries (which seems unlikely).
