### ISSUE TITLE
Color of the image diminishes

### ISSUE THREAD

**Issue by arvind2894** [tjko/jpegoptim#31]
## ORIGINAL:
![Original](https://cloud.githubusercontent.com/assets/10404737/11209364/9a7e4168-8d46-11e5-935f-c00b429057af.jpg)
## AFTER OPTIMIZATION:
![After optimization](https://cloud.githubusercontent.com/assets/10404737/11209374/a834d042-8d46-11e5-92e4-c7ac3c0ed794.jpg)
### Command Used:
```shell
jpegoptim ch5_BW_adjustment.jpg -m50 -s
```
On performing the optimization of the image, the image color modifies as the extra blue screen placed over it. It even happens with more images whose base color is blue (the images mostly contains sky).

###### Image is downloaded from http://www.creativedigitaldarkroom.com/Downloads.html

**Comment by aradeonas** [comment]
It because you striped ICC profile from Exif with -s.
As I know there isn't any option in jpegoptim to strip except ICC profile or apply color profile to image while compressing.
So If you remove -s it will solve your problem.

**Comment by arvind2894** [comment]
@aradeonas  Thanks. There are multiple options to be used to strip the image without stripping ICC profile. Thanks for pointing it out
