### ISSUE TITLE
php cron jpegoptim --preserve-perms

### ISSUE THREAD

**Issue by Groonya** [tjko/jpegoptim#37]
When jpegoptim runs in php (shell_exec command) by cron key --preserve-perms not working. If only by php (without cron) all working properly.

**Comment by Onyx808** [comment]
running into the same issue here, when running the command in cron it does not preserve the files permissions, ideas?

**Comment by Onyx808** [comment]
Sorry, I was running version 1.3, upgraded to 1.4.3 and permissions are preserved correctly.
