### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [tjko/jpegoptim#38]
I would like to point out that an identifier like "[`_JPEGOPTIM_H`](https://github.com/tjko/jpegoptim/blob/2220392455d0600da38c78b2bae681de7c3988a1/jpegoptim.h#L6)" [does not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51-CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not use identifiers that are reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by tjko** [comment]
Thanks. Yes, you're correct _ (underscore) in the beginning of a macro name makes it technically noncompliant. I cleaned those up...

**Comment by elfring** [comment]
Thanks for [your improvement of affected include guards](https://github.com/tjko/jpegoptim/commit/604677c66d645440524260486569fd3c3d7f4d20 "Deletion of a few underscores").
