### ISSUE TITLE
Dest option not working

### ISSUE THREAD

**Issue by xahon** [tjko/jpegoptim#42]
It seems like `-d, --dest` argument not working.

`jpegoptim -m60 *.jpg -d 'comp'`

Returns

`jpegoptim: invalid argument for option -d, --dest`

**Comment by Onyx808** [comment]
Try
`jpegoptim *.jpg -m60 -d comp/`

**Comment by tjko** [comment]
-d option requires existing directory as argument.

Error reporting should now be bit better with this change: 087a8d00cf82cd0f67d2fba5047a430c4e0c6da3
