### ISSUE TITLE
A memory leak vulnerability in jpegoptim.c

### ISSUE THREAD

**Issue by bestshow** [tjko/jpegoptim#44]
on RELEASE.1.4.4

I have found a memory leak vulnerability in jpegoptim.c
https://github.com/tjko/jpegoptim/blob/master/jpegoptim.c#L673
![image](https://cloud.githubusercontent.com/assets/5211744/24813124/7079b85e-1bff-11e7-82bc-8670acf0d28c.png)
The pointer outbuffer was leaked.

**Comment by tjko** [comment]
What exactly is leaked?  How is this vulnerability?

Yes, malloc() returns "unitialized" buffer, but thats ok, since we don't care what is there (it's just temp memory for writing new jpeg file image)....

**Comment by Dev-B-V-A** [comment]
You have problem with memmory, which hasn't been removed. You should call free () for "outbuffer".
