### ISSUE TITLE
Fedora 25, not install jpegoptim.

### ISSUE THREAD

**Issue by AlekseyPn** [tjko/jpegoptim#47]
npm during the installation check that alert
`  ⚠ The `/home/fargustian/node_modules/jpegoptim-bin/vendor/jpegoptim` binary doesn't seem to work correctly
  ⚠ jpegoptim pre-build test failed
  ℹ compiling from source`

After I trying compilation my build, but jpeg image not optimization.

I've tried all that google gave me on this problem.

Help me please :)

**Comment by AlekseyPn** [comment]
Compilation error
`(node:7356) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 12): Error in plugin 'gulp-image'
Message:
    write EPIPE
Details:
    code: EPIPE
    errno: EPIPE
    syscall: write
    killed: false
    stdout: 
    stderr: /home/fargustian/develop/fabba/fabba-app/node_modules/jpegoptim-bin/vendor/jpegoptim: error while loading shared libraries: libjpeg.so.8: cannot open shared object file: No such file or directory

    failed: true
    signal: null
    cmd: /home/fargustian/develop/fabba/fabba-app/node_modules/jpegoptim-bin/vendor/jpegoptim --strip-all --strip-iptc --strip-icc --stdin --stdout
    timedOut: false
`

**Comment by AlekseyPn** [comment]
> jpegoptim-bin@3.0.0 postinstall /home/fargustian/Develop/Work/fabba/fabba-app/node_modules/jpegoptim-bin
> node lib/install.js

  ⚠ The `/home/fargustian/Develop/Work/fabba/fabba-app/node_modules/jpegoptim-bin/vendor/jpegoptim` binary doesn't seem to work correctly
  ⚠ jpegoptim pre-build test failed
  ℹ compiling from source
  ✖ Error: ./configure --prefix="/home/fargustian/Develop/Work/fabba/fabba-app/node_modules/jpegoptim-bin/vendor" --bindir="/home/fargustian/Develop/Work/fabba/fabba-app/node_modules/jpegoptim-bin/vendor" && make install
Command failed: ./configure --prefix="/home/fargustian/Develop/Work/fabba/fabba-app/node_modules/jpegoptim-bin/vendor" --bindir="/home/fargustian/Develop/Work/fabba/fabba-app/node_modules/jpegoptim-bin/vendor"

    at ChildProcess.exithandler (child_process.js:204:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:891:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
Now error look that/Linux Fedora 26,  this only package which is not installed in my build.

**Comment by HorselessHorseman** [comment]
Have you installed the necessary packages such as libjpeg8-dev, autoconf, automake?
