### ISSUE TITLE
Honour umask when generating images

### ISSUE THREAD

**Issue by Muffinman** [tjko/jpegoptim#48]
Is there any reason why this project does not honour the user's umask when creating new files? It seems pretty strange to me :D

I can understand the need for the `--preserve-perms` flag (and I think that's a great idea), but the default creation with 600 seems a little odd to me.

With 600 perms it will often mean that a webserver can't read or serve the files, and I imagine web-image optimisation a big proportion of the people using this project.

**Comment by tjko** [comment]
Current behavior is to keep file 'mode' same as in the original file.
