### ISSUE TITLE
file .tmp instead jpg

### ISSUE THREAD

**Issue by semiromid** [tjko/jpegoptim#54]
files with extension .tmp instead jpg

When i use --dest=tested2 tested1/Auth.jpg
folder tested2 have filename to - `jpegoptim-0-3044.1509186652.tmp` **instead** `Auth.jpg`

I use win 8.1 x64
I try win 7 x32

**Comment by iursevla** [comment]
Same thing happening to me.

**Comment by semiromid** [comment]
@iursevla 

This problem was due to wrong slash

It is worked:
`"J:\111\jpegoptim-64.exe" --all-progressive -d b\1 a\olQ9Dqr.jpg`
