### ISSUE TITLE
Official Windows builds

### ISSUE THREAD

**Issue by XhmikosR** [tjko/jpegoptim#63]
@tjko: I've been using my own builds for a long time, see https://github.com/XhmikosR/jpegoptim-windows

How about adding official Windows builds here with AppVeyor/GitHub Actions CI like I've done on my repo?

**Comment by tjko** [comment]
Is there examples to do builds just with CMake etc (wouldn't want to maintain Visual Studio project files, etc..) ?

It would be nice to have action that builds Linux, MacOS, and Windows binaries automatically....  Doing quick search didn't seem to yield good examples how to achieve that though...

**Comment by XhmikosR** [comment]
I guess you could look at mozjpeg's CI. The reason I went with VS solution files is that it was easier for me to customize the compiler and linker options, but I'm pretty sure this can be done with CMake too. It just needs someone to read their docs.
