### ISSUE TITLE
file name like -2vfzszxJvBJiPA2djxJKv2ruKBUaehm.jpg

### ISSUE THREAD

**Issue by anpsoft** [tjko/jpegoptim#64]
this utilites not work with file names started from "-"
like -2vfzszxJvBJiPA2djxJKv2ruKBUaehm.jpg

D:\Utils\jpegoptim -f -S70 -m70 --strip-all *.jpg
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- 2
d:\iranpdoc\MyScripts\Utils\jpegoptim: invalid option -- z
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- s
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- z
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- x
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- J
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- B
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- J
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- i
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- P
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- A
d:\anpdoc\MyScripts\Utils\jpegoptim: invalid option -- 2
jpegoptim: invalid argument for option -d, --dest.

**Comment by tjko** [comment]
You can use "--" to indicate that any following arguments should be treated as files (even if they start with "-").

So something like this should work:
```
jpegoptim -f -S70 -m70 --strip-all -- *.jpg
```

However, looks like there was bug preventing this from working correctly, this has now been fixed
with following commit: cf9d98189d9681d81c0642e66d853afb8fc67c15
