### ISSUE TITLE
Man page typos

### ISSUE THREAD

**Issue by jidanni** [tjko/jpegoptim#68]
Two typos on the man page:
 
      --all-normal Force all output files to be non-progressive. Can be
             used to convert all input files to progressive JPEGs when
                                          >>>   ^NON-   <<<
             used with --force option.

       --all-progressive Force all output files to be progressive. Can
             be used to convert all normal (non-progressive) JPEGs input
             files to progressive when used with --force option.

       --stdin Read input image from standard input. When this option is
             used then only one image is read from standard XXoutputXX. <<< INPUT

**Comment by tjko** [comment]
Thanks for pointing these out.  These are now fixed e0aeb995912e3c4790cebafedcdf93791e2f68fd
